
name: Compile The New Version OpenClash

on: 
  workflow_dispatch:
  push:

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Building packages
        run: |
            git clone --depth 1 https://github.com/vernesong/OpenClash.git luci-app-openclash2
            mv luci-app-openclash2/luci-app-openclash .
            rm -rf luci-app-openclash2

      - name: New Version
        id: version
        run: |
          echo "version=$(grep 'PKG_VERSION:=' ./luci-app-openclash/Makefile |awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "New Version: $(grep 'PKG_VERSION:=' ./luci-app-openclash/Makefile |awk -F '=' '{print $2}')"

      - name: Apt Update
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install curl git tar

      - name: Install OpenWrt SDK
        run: |
          cd ..
          mkdir tmp
          curl -SLk --connect-timeout 30 --retry 2 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "./tmp/SDK.tar.bz2"
          cd \tmp
          tar xjf SDK.tar.bz2
          mv "OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64" "SDK"

      - name: Copy OpenClash Source Codes
        run: |
          echo ${{ github.workspace }}
          cd ..
          mkdir tmp/SDK/package/luci-app-openclash
          ls
          cp -rf "${{ github.workspace }}/." "./tmp/SDK/package/luci-app-openclash/"

      - name: Compile po2lmo
        run: |
          cd ..
          cd tmp/SDK/package/
          pushd luci-app-openclash/tools/po2lmo
          make && sudo make install
          popd

      - name: Compile OpenClash IPK
        run: |
          cd ..
          cd tmp/SDK
          make package/luci-app-openclash/compile V=99

      - name: Store packages
        uses: actions/upload-artifact@main
        with:
          name: Openclash
          path: ./tmp/SDK/bin/ar71xx/packages/base/luci-app-openclash*.ipk